apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/bechernie/dispatcher-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-service

images:
- name: dispatcher-service
  newName: ghcr.io/bechernie/dispatcher-service
  newTag: 7fe55ebc44445639e68a08bc9adc8793ebd0aac0

replicas:
- count: 2
  name: dispatcher-service
