apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/bechernie/edge-service/k8s?ref=main

patches:
  - path: patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: edge-service

images:
  - name: edge-service
    newName: ghcr.io/polarbookshop/edge-service
    newTag: latest

replicas:
  - name: edge-service
    count: 2