apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/bechernie/catalog-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-service

images:
- name: catalog-service
  newName: ghcr.io/bechernie/catalog-service
  newTag: 63ce27468476b479d89b3fa6b5e3e6d7d4f1824f

replicas:
- count: 2
  name: catalog-service
