apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/bechernie/catalog-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-service

images:
- name: catalog-service
  newName: ghcr.io/bechernie/catalog-service
  newTag: 66702b0dc5c5d42cfbb8a847ca7ee82e77d7a8af

replicas:
- count: 2
  name: catalog-service
