apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          resources:
            requests:
              memory: 726Mi
              cpu: "0.1"
            limits:
              memory: 726Mi
              cpu: "2"
