apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/bechernie/order-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-service

images:
- name: order-service
  newName: ghcr.io/bechernie/order-service
  newTag: b5ad3ca0ac37517969e080a5015079e6331ad8f1

replicas:
- count: 2
  name: order-service
