apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/bechernie/edge-service/k8s?ref=main

patches:
- path: patch-ingress.yml
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service

images:
- name: edge-service
  newName: ghcr.io/bechernie/edge-service
  newTag: c1886e10074364d59db0e1d4c746085f09a1ec09

replicas:
- count: 2
  name: edge-service
